import type { Card } from './types';

export const SENTENCE_CARDS: Card[] = [
  // ===================== s-opinion =====================
  {
    id: 's_1',
    module: 'sentences',
    topic: 's-opinion',
    band: 'b6',
    type: 'structure',
    tags: ['opinion', 'personal', 'thesis'],
    title: 'Nêu quan điểm cá nhân: I firmly believe / In my view',
    ans: {
      summary:
        "Dùng để mở bài hoặc kết bài khi cần tuyên bố rõ lập trường của bạn. Sắc thái trực tiếp, mạnh mẽ, phù hợp với câu hỏi dạng To what extent / Do you agree.",
      points: [
        "Công thức: I (firmly/strongly) believe that + mệnh đề; In my view/opinion, + mệnh đề.",
        "Sau \"believe that\" luôn là một mệnh đề đầy đủ (S + V), không phải danh từ đơn.",
        "Tránh lặp \"I think\" quá nhiều; dùng các biến thể để nâng band.",
      ],
      phrases: [
        "I firmly believe that + [clause]",
        "In my view, + [clause]",
        "From my perspective, + [clause]",
        "I am convinced that + [clause]",
      ],
      examples: [
        "I firmly believe that governments should invest more heavily in renewable energy.",
        "In my view, online learning can never fully replace traditional classroom teaching.",
        "From my perspective, the benefits of urban green spaces clearly outweigh the costs.",
        "I am convinced that stricter penalties alone will not reduce the crime rate.",
        "I firmly believe that children benefit enormously from learning a second language at an early age.",
        "In my view, social media has done more harm than good to genuine human relationships.",
        "From my perspective, raising taxes on unhealthy food is an effective way to tackle obesity.",
        "I am convinced that flexible working hours improve both productivity and employee well-being.",
        "I firmly believe that public transport should be subsidised to ease traffic congestion in cities.",
        "In my view, the media has a responsibility to report news accurately rather than sensationally.",
      ],
      sample:
        "In my view, the rapid growth of private vehicle ownership lies at the heart of urban congestion.\nI firmly believe that only sustained investment in public transport can reverse this trend.",
    },
  },
  {
    id: 's_2',
    module: 'sentences',
    topic: 's-opinion',
    band: 'b7',
    type: 'structure',
    tags: ['opinion', 'impersonal', 'passive'],
    title: 'Quan điểm phi cá nhân: It is often argued that...',
    ans: {
      summary:
        "Dùng để trình bày một quan điểm phổ biến trong xã hội mà không gắn với cái tôi, giúp văn phong khách quan và học thuật hơn. Thường dùng ở mở bài để dẫn dắt vấn đề.",
      points: [
        "Công thức: It is + (often/widely/commonly) + V-ed (argued/believed/held/claimed) + that + mệnh đề.",
        "Đây là cấu trúc bị động phi nhân xưng (impersonal passive), nâng tính khách quan.",
        "Có thể nối tiếp bằng \"However, I would argue that...\" để chuyển sang quan điểm riêng.",
      ],
      phrases: [
        "It is often argued that + [clause]",
        "It is widely believed that + [clause]",
        "It is commonly held that + [clause]",
        "It is frequently claimed that + [clause]",
      ],
      examples: [
        "It is often argued that technology has made people more isolated than ever before.",
        "It is widely believed that a university degree guarantees a well-paid job.",
        "It is commonly held that strict laws are the most effective way to deter crime.",
        "It is frequently claimed that globalisation threatens local cultures and traditions.",
        "It is often argued that working from home reduces overall productivity.",
        "It is widely believed that government funding for the arts is a waste of public money.",
        "It is commonly held that early exposure to screens harms children's development.",
        "It is frequently claimed that economic growth inevitably damages the environment.",
        "It is often argued that the news media exaggerate problems to attract audiences.",
        "It is widely believed that urbanisation has weakened traditional family ties.",
      ],
      sample:
        "It is widely believed that economic development and environmental protection cannot go hand in hand.\nHowever, I would argue that the right policies can allow nations to pursue both goals at once.",
    },
  },
  {
    id: 's_3',
    module: 'sentences',
    topic: 's-opinion',
    band: 'b7',
    type: 'structure',
    tags: ['opinion', 'agreement', 'strong'],
    title: 'Đồng ý hoàn toàn: I completely agree that...',
    ans: {
      summary:
        "Dùng khi đề bài yêu cầu thể hiện mức độ đồng ý và bạn muốn ủng hộ mạnh mẽ một ý kiến. Sắc thái dứt khoát, thể hiện lập trường rõ ràng.",
      points: [
        "Công thức: I completely/wholeheartedly agree that + mệnh đề; There is no doubt that + mệnh đề.",
        "Dùng trạng từ tăng cường (completely, entirely, wholeheartedly) để thể hiện mức độ.",
        "Tránh nói \"I agree 100%\"; văn viết học thuật dùng từ ngữ trang trọng hơn.",
      ],
      phrases: [
        "I completely agree that + [clause]",
        "There is no doubt that + [clause]",
        "I wholeheartedly support the view that + [clause]",
        "Without question, + [clause]",
      ],
      examples: [
        "I completely agree that protecting endangered species must be a global priority.",
        "There is no doubt that regular exercise significantly improves mental health.",
        "I wholeheartedly support the view that education should be free at the point of use.",
        "Without question, the internet has transformed the way we access information.",
        "I completely agree that companies should be held accountable for the pollution they cause.",
        "There is no doubt that a healthy diet plays a crucial role in preventing disease.",
        "I wholeheartedly support the view that reading widely improves children's academic performance.",
        "Without question, public investment in renewable energy will benefit future generations.",
        "I completely agree that traffic congestion in major cities has reached crisis levels.",
        "There is no doubt that fake news poses a serious threat to democratic societies.",
      ],
      sample:
        "There is no doubt that climate change represents the greatest challenge of our era.\nI completely agree that immediate and coordinated action is needed to limit its worst effects.",
    },
  },
  {
    id: 's_4',
    module: 'sentences',
    topic: 's-opinion',
    band: 'b8',
    type: 'structure',
    tags: ['opinion', 'partial agreement', 'balanced'],
    title: 'Đồng ý một phần: While I agree to some extent...',
    ans: {
      summary:
        "Dùng cho lập trường cân bằng (partly agree), rất hữu ích với câu hỏi To what extent. Sắc thái tinh tế, thể hiện tư duy phản biện và độ chín của lập luận.",
      points: [
        "Công thức: While I agree (that) + mệnh đề, I believe + mệnh đề trái chiều.",
        "Cấu trúc \"to a certain extent / up to a point\" giúp diễn đạt mức độ đồng ý hạn chế.",
        "Lưu ý cân bằng: phải nêu cả phần đồng ý lẫn phần dè dặt, không bỏ dở một vế.",
      ],
      phrases: [
        "While I agree to some extent that..., I believe + [clause]",
        "I partly agree with the view that + [clause]",
        "Although there is some truth in this argument, + [clause]",
        "This is true up to a point, but + [clause]",
      ],
      examples: [
        "While I agree to some extent that technology causes distraction, I believe it is an indispensable learning tool.",
        "I partly agree with the view that competition motivates students, although it can also create unhealthy pressure.",
        "Although there is some truth in this argument, the economic benefits of tourism cannot be ignored.",
        "This is true up to a point, but blaming individuals overlooks the role of large corporations in pollution.",
        "While I agree to some extent that fast food is harmful, I believe consumers should bear some responsibility for their choices.",
        "I partly agree with the view that remote work isolates employees, yet it also offers valuable flexibility.",
        "Although there is some truth in this argument, strict censorship can undermine freedom of expression.",
        "This is true up to a point, but cities still need cars for essential services and emergencies.",
        "While I agree to some extent that the media exaggerates crime, public concern is not entirely unfounded.",
        "I partly agree with the view that money brings happiness, although emotional well-being matters far more.",
      ],
      sample:
        "While I agree to some extent that social media fuels anxiety among teenagers, I believe the platforms themselves are not solely to blame.\nMuch depends on how parents and schools guide young people to use these tools responsibly.",
    },
  },
  {
    id: 's_5',
    module: 'sentences',
    topic: 's-opinion',
    band: 'b8',
    type: 'structure',
    tags: ['opinion', 'hedging', 'caution'],
    title: 'Ngôn ngữ dè dặt (hedging): tend to / arguably / may well',
    ans: {
      summary:
        "Dùng để diễn đạt cẩn trọng, tránh khẳng định tuyệt đối khiến lập luận dễ bị phản bác. Đây là dấu hiệu của band 8: nhận thức được giới hạn của nhận định.",
      points: [
        "Công cụ hedging: tend to + V, may/might well + V, arguably, in many cases, it is likely that.",
        "Đặt \"tend to\" giữa S và V; \"arguably\" thường đứng đầu câu hoặc trước tính từ so sánh.",
        "Lưu ý: hedging không phải là viết mơ hồ; vẫn phải có quan điểm rõ ràng, chỉ là dè dặt về mức độ.",
      ],
      phrases: [
        "[Subject] tend(s) to + [verb]",
        "[Subject] may well + [verb]",
        "Arguably, + [clause]",
        "In many cases, + [clause]",
        "It is likely that + [clause]",
      ],
      examples: [
        "Children who read regularly tend to perform better academically than those who do not.",
        "Stricter regulations may well discourage small businesses from entering the market.",
        "Arguably, the most pressing issue facing modern cities is air pollution.",
        "In many cases, people move to urban areas in search of better job opportunities.",
        "It is likely that automation will replace a significant proportion of manual jobs.",
        "Wealthier nations tend to consume far more energy per capita than developing ones.",
        "Banning advertisements aimed at children may well reduce rates of childhood obesity.",
        "Arguably, online education has widened rather than narrowed the gap between rich and poor.",
        "In many cases, exposure to nature appears to lower stress and improve concentration.",
        "It is likely that an ageing population will place growing pressure on healthcare systems.",
      ],
      sample:
        "Heavy users of social media tend to report higher levels of anxiety than their peers.\nWhile the evidence is not conclusive, it is likely that constant comparison plays a significant role, and the problem may well worsen as platforms become more pervasive.",
    },
  },
  {
    id: 's_6',
    module: 'sentences',
    topic: 's-opinion',
    band: 'b7',
    type: 'structure',
    tags: ['opinion', 'recommendation', 'should'],
    title: 'Đề xuất giải pháp: ...should... / It would be advisable to...',
    ans: {
      summary:
        "Dùng trong đoạn giải pháp hoặc kết bài để khuyến nghị hành động. Sắc thái mang tính tư vấn, hướng tới giải quyết vấn đề.",
      points: [
        "Công thức: [Subject] should/ought to + V (bare); It would be advisable/sensible to + V.",
        "Dùng \"need to\" cho mức độ cần thiết cao hơn \"should\".",
        "Tránh lạm dụng \"must\"; trong văn nghị luận \"should\" thường tự nhiên hơn.",
      ],
      phrases: [
        "[Subject] should + [verb]",
        "It would be advisable to + [verb]",
        "One effective solution would be to + [verb]",
        "Governments ought to + [verb]",
      ],
      examples: [
        "Governments should invest in cycling infrastructure to reduce reliance on cars.",
        "It would be advisable to introduce digital literacy lessons in primary schools.",
        "One effective solution would be to impose higher taxes on heavily polluting industries.",
        "Employers ought to provide regular training to help staff adapt to new technology.",
        "Schools should place greater emphasis on practical skills alongside academic subjects.",
        "It would be advisable to limit the amount of advertising directed at young children.",
        "One effective solution would be to expand affordable housing in city centres.",
        "Authorities should prioritise rehabilitation over imprisonment for minor offences.",
        "Parents ought to monitor how much time their children spend in front of screens.",
        "It would be sensible to raise public awareness about the dangers of a sedentary lifestyle.",
      ],
      sample:
        "To tackle rising obesity, governments should regulate the marketing of junk food more strictly.\nIn addition, it would be advisable to fund community programmes that make exercise accessible to all.",
    },
  },

  // ===================== s-cause =====================
  {
    id: 's_7',
    module: 'sentences',
    topic: 's-cause',
    band: 'b6',
    type: 'structure',
    tags: ['cause', 'connectors', 'because'],
    title: 'Liên từ chỉ nguyên nhân: because / since / as',
    ans: {
      summary:
        "Dùng để nối nguyên nhân với kết quả trong cùng một câu. Đây là nhóm liên từ cơ bản nhưng cực kỳ phổ biến và an toàn.",
      points: [
        "Công thức: [Result], because/since/as + [mệnh đề nguyên nhân]. Hoặc đặt mệnh đề nguyên nhân lên đầu.",
        "Sau because/since/as luôn là mệnh đề (S + V), KHÔNG phải danh từ.",
        "Khi mệnh đề nguyên nhân đứng đầu câu, dùng dấu phẩy ngăn cách hai vế.",
      ],
      phrases: [
        "[clause], because + [clause]",
        "Since + [clause], [clause]",
        "As + [clause], [clause]",
      ],
      examples: [
        "Many young people move to cities because there are more job opportunities there.",
        "Since fossil fuels are running out, countries must develop alternative energy sources.",
        "As the population continues to grow, demand for housing is rising sharply.",
        "Obesity rates have soared because people consume too much processed food.",
        "Since online shopping is so convenient, many traditional stores have closed down.",
        "As public transport is unreliable in many areas, residents depend heavily on cars.",
        "Crime tends to rise in deprived areas because residents lack stable employment.",
        "Since technology evolves so quickly, workers must constantly update their skills.",
        "As more women join the workforce, demand for affordable childcare has increased.",
        "Students often feel stressed because they face intense pressure to achieve high grades.",
      ],
      sample:
        "Air quality in many cities has deteriorated because the number of private vehicles keeps rising.\nSince public transport remains underfunded, commuters have little choice but to drive.",
    },
  },
  {
    id: 's_8',
    module: 'sentences',
    topic: 's-cause',
    band: 'b7',
    type: 'structure',
    tags: ['cause', 'preposition', 'noun phrase'],
    title: 'Nguyên nhân + danh từ: due to / owing to / because of',
    ans: {
      summary:
        "Dùng khi muốn nêu nguyên nhân bằng một cụm danh từ thay vì cả mệnh đề, giúp câu gọn gàng và đa dạng cấu trúc.",
      points: [
        "Công thức: due to / owing to / because of + DANH TỪ / cụm danh từ (KHÔNG phải mệnh đề).",
        "Muốn theo sau bằng mệnh đề thì viết: due to the fact that + [mệnh đề].",
        "Lưu ý: \"due to\" thường theo sau động từ to be; \"owing to\" trang trọng hơn.",
      ],
      phrases: [
        "due to + [noun phrase]",
        "owing to + [noun phrase]",
        "because of + [noun phrase]",
        "as a result of + [noun phrase]",
      ],
      examples: [
        "Many species are now endangered due to the destruction of their natural habitats.",
        "Owing to rapid urbanisation, farmland on the edge of cities is disappearing fast.",
        "Air pollution has worsened because of the growing number of vehicles on the roads.",
        "As a result of automation, thousands of factory workers have lost their jobs.",
        "Childhood obesity has risen sharply due to a combination of poor diet and inactivity.",
        "Owing to the high cost of housing, many young adults still live with their parents.",
        "Crime rates often increase because of widespread unemployment and poverty.",
        "As a result of climate change, extreme weather events are becoming more frequent.",
        "Many small shops have closed due to competition from large online retailers.",
        "Owing to advances in medicine, average life expectancy has risen considerably.",
      ],
      sample:
        "Coastal communities are increasingly at risk owing to rising sea levels.\nDue to decades of unchecked carbon emissions, these effects are now extremely difficult to reverse.",
    },
  },
  {
    id: 's_9',
    module: 'sentences',
    topic: 's-cause',
    band: 'b6',
    type: 'structure',
    tags: ['cause', 'result', 'connectors'],
    title: 'Liên từ chỉ kết quả: therefore / consequently / as a result',
    ans: {
      summary:
        "Dùng để mở đầu câu nêu kết quả/hệ quả, nối ý mạch lạc giữa hai câu. Sắc thái logic, học thuật.",
      points: [
        "Công thức: [Câu nguyên nhân]. Therefore/Consequently/As a result, [câu kết quả].",
        "Các trạng từ này đứng đầu câu và theo sau bằng dấu phẩy; nối hai CÂU riêng biệt.",
        "Nếu muốn nối trong một câu, dùng dấu chấm phẩy: ...; therefore, ...",
      ],
      phrases: [
        "Therefore, + [clause]",
        "Consequently, + [clause]",
        "As a result, + [clause]",
        "Thus, + [clause]",
        "For this reason, + [clause]",
      ],
      examples: [
        "Fuel prices have risen sharply. Therefore, more commuters are switching to public transport.",
        "The factory dumped waste into the river. Consequently, local fish stocks collapsed.",
        "Many graduates lack practical experience. As a result, employers struggle to fill skilled positions.",
        "The city expanded its cycle lanes. Thus, the number of cyclists doubled within two years.",
        "Junk food is cheap and heavily advertised. For this reason, obesity rates continue to climb.",
        "Working hours have grown longer. Consequently, many employees report higher levels of stress.",
        "Renewable energy has become cheaper. Therefore, more households are installing solar panels.",
        "The government cut funding for the arts. As a result, several museums were forced to close.",
        "Screens now dominate daily life. Thus, children spend far less time playing outdoors.",
        "Antibiotics have been overused for decades. Consequently, drug-resistant bacteria are spreading.",
      ],
      sample:
        "Years of overfishing have depleted marine populations across the region.\nAs a result, many coastal communities have lost their main source of income, and entire fishing industries have collapsed.",
    },
  },
  {
    id: 's_10',
    module: 'sentences',
    topic: 's-cause',
    band: 'b7',
    type: 'structure',
    tags: ['cause', 'verbs', 'lead to'],
    title: 'Động từ nhân quả: lead to / result in / give rise to',
    ans: {
      summary:
        "Dùng động từ để diễn đạt mối quan hệ nhân quả, giúp câu sinh động và đa dạng hơn so với liên từ. Rất hữu ích cho cả nguyên nhân lẫn kết quả.",
      points: [
        "Công thức: [Nguyên nhân] + lead to / result in / give rise to + DANH TỪ / V-ing (kết quả).",
        "Chiều ngược lại: [Kết quả] + result from / stem from / be attributed to + DANH TỪ (nguyên nhân).",
        "Lưu ý: sau các động từ này là danh từ hoặc V-ing, không phải mệnh đề.",
      ],
      phrases: [
        "[cause] leads to + [noun/V-ing]",
        "[cause] results in + [noun/V-ing]",
        "[cause] gives rise to + [noun]",
        "[result] stems from + [noun]",
        "[result] can be attributed to + [noun]",
      ],
      examples: [
        "Deforestation leads to soil erosion and the loss of countless species.",
        "Excessive screen time can result in poor sleep and reduced concentration in children.",
        "Rapid urbanisation has given rise to overcrowding and inadequate housing.",
        "Much of today's pollution stems from our continued dependence on fossil fuels.",
        "The recent fall in crime can be attributed to better community policing.",
        "Poor diet and a lack of exercise frequently lead to serious health problems.",
        "Heavy investment in education often results in stronger long-term economic growth.",
        "Unrestricted industrial expansion has given rise to widespread environmental damage.",
        "Rising youth unemployment largely stems from a mismatch between skills and job demands.",
        "The growing popularity of remote work can be attributed to advances in communication technology.",
      ],
      sample:
        "Unplanned urban growth often leads to severe traffic congestion and air pollution.\nThese problems, in turn, give rise to health issues that can be directly attributed to poor city planning.",
    },
  },
  {
    id: 's_11',
    module: 'sentences',
    topic: 's-cause',
    band: 'b8',
    type: 'structure',
    tags: ['cause', 'chain', 'reasoning'],
    title: 'Chuỗi lập luận nhân quả (chain of reasoning)',
    ans: {
      summary:
        "Dùng để trình bày một chuỗi nguyên nhân - kết quả nhiều bước, cho thấy tư duy logic sâu. Đây là kỹ năng then chốt để phát triển ý ở band 8.",
      points: [
        "Công thức: A leads to B, which in turn results in C. Hoặc: A. This, in turn, ... Ultimately, ...",
        "Dùng \"which in turn\", \"this, in turn\", \"ultimately\", \"eventually\" để nối các mắt xích.",
        "Lưu ý: mỗi bước phải hợp lý; tránh nhảy cóc khiến lập luận thiếu thuyết phục.",
      ],
      phrases: [
        "[A] leads to [B], which in turn results in [C]",
        "This, in turn, + [clause]",
        "Ultimately, + [clause]",
        "This sets off a chain reaction in which + [clause]",
      ],
      examples: [
        "Cutting down forests reduces rainfall, which in turn lowers crop yields and threatens food security.",
        "Job losses reduce household income; this, in turn, weakens consumer spending and slows the economy.",
        "Heavy traffic increases air pollution, which leads to respiratory illness and, ultimately, higher healthcare costs.",
        "Poor schooling limits employment prospects; this, in turn, traps families in a cycle of poverty.",
        "Burning fossil fuels raises global temperatures, which melts polar ice and ultimately drives sea levels higher.",
        "Excessive use of social media disrupts sleep, which in turn impairs concentration and academic performance.",
        "Overfishing depletes fish stocks, which damages marine ecosystems and ultimately destroys coastal livelihoods.",
        "Rising rents force people to the city outskirts; this, in turn, lengthens commutes and worsens congestion.",
        "Antibiotic overuse breeds resistant bacteria, which makes infections harder to treat and ultimately costs lives.",
        "Automation eliminates routine jobs, which widens inequality and, in turn, fuels social unrest.",
      ],
      sample:
        "When forests are cleared for farmland, the soil quickly loses its fertility.\nThis, in turn, forces farmers to clear even more land, and ultimately the cycle accelerates the very deforestation that triggered the problem in the first place.",
    },
  },

  // ===================== s-concession =====================
  {
    id: 's_12',
    module: 'sentences',
    topic: 's-concession',
    band: 'b6',
    type: 'structure',
    tags: ['concession', 'although', 'clause'],
    title: 'Nhượng bộ với mệnh đề: although / even though / though',
    ans: {
      summary:
        "Dùng để thừa nhận một ý đối lập trước khi nêu quan điểm chính, thể hiện tư duy hai chiều. Sắc thái cân bằng, thuyết phục.",
      points: [
        "Công thức: Although/Even though/Though + [mệnh đề nhượng bộ], [mệnh đề chính].",
        "Sau although/even though là mệnh đề (S + V); KHÔNG dùng \"but\" ở vế chính (tránh lặp).",
        "\"Even though\" mạnh hơn \"although\"; \"though\" có thể đứng cuối câu (informal hơn).",
      ],
      phrases: [
        "Although + [clause], [clause]",
        "Even though + [clause], [clause]",
        "Though + [clause], [clause]",
      ],
      examples: [
        "Although online courses are convenient, they cannot replace face-to-face interaction.",
        "Even though renewable energy is expensive to install, it pays off in the long run.",
        "Although tourism boosts the economy, it can place enormous strain on local resources.",
        "Even though strict laws exist, many drivers still ignore basic safety rules.",
        "Although technology connects us instantly, it can also make relationships more superficial.",
        "Even though wages have risen, the cost of living has increased even faster.",
        "Although recycling is widely promoted, participation rates remain disappointingly low.",
        "Even though the city built new roads, traffic congestion has barely improved.",
        "Although working from home saves commuting time, it can blur the line between work and rest.",
        "Even though vaccines are freely available, some communities remain hesitant to use them.",
      ],
      sample:
        "Although mass tourism generates substantial income for coastal towns, it often comes at a heavy environmental cost.\nFragile ecosystems are damaged, and local residents are gradually priced out of their own neighbourhoods.",
    },
  },
  {
    id: 's_13',
    module: 'sentences',
    topic: 's-concession',
    band: 'b7',
    type: 'structure',
    tags: ['concession', 'preposition', 'despite'],
    title: 'Nhượng bộ + danh từ: despite / in spite of',
    ans: {
      summary:
        "Dùng để thừa nhận một thực tế đối lập bằng cụm danh từ, làm câu gọn và đa dạng. Tương đương về nghĩa với although nhưng khác cấu trúc.",
      points: [
        "Công thức: Despite / In spite of + DANH TỪ / V-ing, [mệnh đề chính].",
        "Muốn theo sau bằng mệnh đề: despite the fact that + [mệnh đề].",
        "Lỗi thường gặp: KHÔNG viết \"despite of\"; chỉ có \"in spite of\" hoặc \"despite\".",
      ],
      phrases: [
        "Despite + [noun/V-ing], [clause]",
        "In spite of + [noun/V-ing], [clause]",
        "Despite the fact that + [clause], [clause]",
      ],
      examples: [
        "Despite the obvious health risks, many people continue to smoke regularly.",
        "In spite of heavy government investment, the public transport system remains overcrowded.",
        "Despite living in an age of information, many citizens struggle to tell fact from fiction.",
        "In spite of rising awareness, plastic waste in the oceans keeps increasing.",
        "Despite earning high salaries, some professionals report little satisfaction with their lives.",
        "In spite of strict regulations, factories continue to release pollutants into rivers.",
        "Despite the convenience of cars, more city dwellers are choosing to cycle to work.",
        "In spite of advances in medicine, preventable diseases still claim millions of lives.",
        "Despite spending billions on education, the country still faces a serious skills shortage.",
        "In spite of the growth of online media, printed newspapers retain a loyal readership.",
      ],
      sample:
        "Despite decades of campaigns warning against the dangers of smoking, the habit remains widespread.\nIn spite of higher taxes and graphic health warnings, millions of people are still unable to give it up.",
    },
  },
  {
    id: 's_14',
    module: 'sentences',
    topic: 's-concession',
    band: 'b8',
    type: 'structure',
    tags: ['concession', 'admittedly', 'rebuttal'],
    title: 'Thừa nhận rồi phản biện: Admittedly,...; however,...',
    ans: {
      summary:
        "Dùng để công nhận một điểm hợp lý của phía đối lập rồi xoay sang bảo vệ quan điểm của mình. Sắc thái khách quan, rất đặc trưng của band 8.",
      points: [
        "Công thức: Admittedly, [ý nhượng bộ]. However, [phản biện / quan điểm chính].",
        "Có thể thay \"Admittedly\" bằng \"It is true that...\", \"Granted,...\".",
        "Lưu ý: vế \"however\" phải đủ mạnh để lật lại ý nhượng bộ, nếu không lập luận sẽ yếu.",
      ],
      phrases: [
        "Admittedly, + [clause]. However, + [clause]",
        "It is true that + [clause]. Nevertheless, + [clause]",
        "Granted, + [clause]. That said, + [clause]",
      ],
      examples: [
        "Admittedly, building new roads can ease congestion in the short term. However, it ultimately encourages more people to drive.",
        "It is true that nuclear power produces no carbon emissions. Nevertheless, the risk of catastrophic accidents cannot be ignored.",
        "Granted, social media helps people stay in touch. That said, it often replaces deeper, face-to-face relationships.",
        "Admittedly, tourism creates many jobs. However, much of the profit flows to foreign companies rather than local communities.",
        "It is true that exams measure certain skills. Nevertheless, they fail to capture creativity and critical thinking.",
        "Granted, automation increases efficiency. That said, it leaves many low-skilled workers without employment.",
        "Admittedly, junk food is affordable and convenient. However, its long-term cost to public health is enormous.",
        "It is true that prisons remove offenders from society. Nevertheless, they often fail to address the causes of crime.",
        "Granted, economic growth lifts people out of poverty. That said, unchecked growth can devastate the environment.",
        "Admittedly, free press can occasionally be irresponsible. However, censorship poses a far greater threat to democracy.",
      ],
      sample:
        "Admittedly, online learning has made education accessible to people who would otherwise be excluded.\nHowever, it cannot fully reproduce the spontaneous discussion and mentorship that a physical classroom provides, and for many learners this remains essential.",
    },
  },
  {
    id: 's_15',
    module: 'sentences',
    topic: 's-concession',
    band: 'b7',
    type: 'structure',
    tags: ['concession', 'while it is true', 'balanced'],
    title: 'While it is true that..., ...',
    ans: {
      summary:
        "Một biến thể linh hoạt của nhượng bộ, gom cả ý thừa nhận và phản biện vào một câu duy nhất. Rất tiện để mở đoạn thân bài cân bằng.",
      points: [
        "Công thức: While it is true that + [ý nhượng bộ], + [quan điểm chính].",
        "Có thể thay bằng \"While + [mệnh đề], ...\" để ngắn gọn hơn.",
        "Lưu ý: hai vế phải thực sự đối lập về nội dung, không chỉ nối ý cùng chiều.",
      ],
      phrases: [
        "While it is true that + [clause], + [clause]",
        "While + [clause], + [clause]",
        "Whilst there is some merit in this, + [clause]",
      ],
      examples: [
        "While it is true that cars offer freedom, they are a major source of urban pollution.",
        "While it is true that English dominates global business, preserving local languages still matters.",
        "While it is true that smartphones aid communication, they can also fuel addiction among the young.",
        "While it is true that fast fashion is cheap, it generates enormous amounts of textile waste.",
        "While it is true that competition drives innovation, it can also widen the gap between rich and poor.",
        "While it is true that immigration brings economic benefits, it can strain public services in the short term.",
        "While it is true that exams motivate study, they often reward memorisation over understanding.",
        "While it is true that the internet democratises information, it also spreads misinformation rapidly.",
        "While it is true that cities offer opportunity, they can be lonely and stressful places to live.",
        "While it is true that recycling helps, reducing consumption in the first place is far more effective.",
      ],
      sample:
        "While it is true that economic globalisation has lifted millions out of poverty, its benefits have been distributed very unevenly.\nMany workers in developed nations have seen their jobs disappear, and the resulting resentment cannot simply be dismissed.",
    },
  },
  {
    id: 's_16',
    module: 'sentences',
    topic: 's-concession',
    band: 'b8',
    type: 'structure',
    tags: ['concession', 'inversion', 'advanced'],
    title: 'Nhượng bộ đảo ngữ: As + adj + as / Much as...',
    ans: {
      summary:
        "Cấu trúc nhượng bộ nâng cao dùng đảo ngữ, gây ấn tượng văn phong và rất hiếm gặp ở bài band thấp. Sắc thái trang trọng, nhấn mạnh.",
      points: [
        "Công thức 1: Adjective + as/though + S + be, [mệnh đề chính]. Ví dụ: Difficult as it is, ...",
        "Công thức 2: Much as + S + V, [mệnh đề chính]. Ví dụ: Much as I admire..., ...",
        "Lưu ý: tính từ/trạng từ được đẩy lên đầu để nhấn mạnh; dùng tiết kiệm để tránh gượng ép.",
      ],
      phrases: [
        "[Adjective] as it is, + [clause]",
        "Much as + [clause], + [clause]",
        "Hard though it may be, + [clause]",
      ],
      examples: [
        "Convenient as private cars are, they remain one of the biggest contributors to air pollution.",
        "Much as people value privacy, they routinely surrender their data to online platforms.",
        "Expensive as renewable energy may seem, it is far cheaper than the long-term cost of climate change.",
        "Hard though it may be, governments must phase out subsidies for fossil fuels.",
        "Popular as fast food is, its impact on public health cannot be ignored.",
        "Much as technology improves our lives, it has also eroded our ability to concentrate.",
        "Tempting as it is to blame individuals, the real responsibility lies with large corporations.",
        "Useful as exams are, they reveal only a narrow slice of a student's true ability.",
        "Much as cities offer opportunity, they often fail to provide affordable housing for ordinary workers.",
        "Important as economic growth is, it should never come at the expense of the environment.",
      ],
      sample:
        "Convenient as it is to shop online, the explosion of home deliveries has created a serious environmental burden.\nMuch as consumers enjoy the speed and choice, the resulting packaging waste and delivery traffic cannot be sustained indefinitely.",
    },
  },

  // ===================== s-comparison =====================
  {
    id: 's_17',
    module: 'sentences',
    topic: 's-comparison',
    band: 'b6',
    type: 'structure',
    tags: ['comparison', 'comparative', 'than'],
    title: 'So sánh hơn: comparative + than',
    ans: {
      summary:
        "Cấu trúc so sánh cơ bản nhất, dùng để đối chiếu hai đối tượng theo một tiêu chí. Nền tảng bắt buộc phải dùng chính xác.",
      points: [
        "Công thức: [A] is + tính từ-er / more + tính từ dài + than + [B].",
        "Tăng cường mức độ: far/much/significantly/considerably + comparative + than.",
        "Lỗi thường gặp: KHÔNG dùng \"more + adj-er\" (more better) và nhớ \"than\", không phải \"then\".",
      ],
      phrases: [
        "[A] is + [comparative] + than + [B]",
        "[A] is far more + [adjective] + than + [B]",
        "[A] is significantly + [comparative] + than + [B]",
      ],
      examples: [
        "Public transport is far cheaper than driving a private car in most large cities.",
        "Renewable energy is becoming significantly more affordable than it was a decade ago.",
        "Online courses are often more flexible than traditional university programmes.",
        "Life in the countryside tends to be quieter and less stressful than life in the city.",
        "Processed foods are usually much cheaper than fresh, healthy alternatives.",
        "Younger workers are generally more comfortable with new technology than older colleagues.",
        "Prevention is far more cost-effective than treatment in most healthcare systems.",
        "Cycling to work is considerably healthier than commuting by car.",
        "Rented accommodation is now more common among young adults than home ownership.",
        "Electric vehicles are becoming more popular than petrol cars in many countries.",
      ],
      sample:
        "Investing in prevention is far more cost-effective than paying for expensive treatments later.\nA population that exercises regularly and eats well is significantly less likely to develop chronic illness than one that does not.",
    },
  },
  {
    id: 's_18',
    module: 'sentences',
    topic: 's-comparison',
    band: 'b7',
    type: 'structure',
    tags: ['comparison', 'similarity', 'phrases'],
    title: 'Tương đồng & tương phản: similar to / in contrast to',
    ans: {
      summary:
        "Dùng để chỉ ra điểm giống hoặc khác giữa hai đối tượng bằng cụm giới từ, giúp đoạn so sánh trôi chảy. Sắc thái khách quan, phân tích.",
      points: [
        "Tương đồng: similar to / the same as / like + DANH TỪ.",
        "Tương phản: in contrast to / unlike / as opposed to + DANH TỪ.",
        "Lưu ý: theo sau là danh từ/cụm danh từ; \"in contrast,\" (có phẩy, không \"to\") mở đầu câu mới.",
      ],
      phrases: [
        "similar to + [noun]",
        "the same as + [noun]",
        "in contrast to + [noun]",
        "unlike + [noun]",
        "as opposed to + [noun]",
      ],
      examples: [
        "Unlike fossil fuels, solar and wind power produce no harmful emissions.",
        "In contrast to rural areas, cities offer abundant employment but little open space.",
        "The challenges facing developing nations are similar to those Europe faced a century ago.",
        "As opposed to memorising facts, modern education increasingly values critical thinking.",
        "Unlike printed books, e-books can be carried anywhere on a single device.",
        "In contrast to traditional classrooms, online learning allows students to study at their own pace.",
        "The diet of city dwellers is often very different from that of people in the countryside.",
        "As opposed to short-term fixes, sustainable solutions address the root of the problem.",
        "Unlike older generations, young people today expect to change careers several times.",
        "In contrast to public hospitals, private clinics often offer shorter waiting times.",
      ],
      sample:
        "Unlike fossil fuels, which release carbon dioxide when burned, renewable sources generate clean electricity.\nIn contrast to the volatile prices of oil and gas, the cost of solar power has fallen steadily for years.",
    },
  },
  {
    id: 's_19',
    module: 'sentences',
    topic: 's-comparison',
    band: 'b7',
    type: 'structure',
    tags: ['comparison', 'contrast', 'whereas'],
    title: 'Tương phản với mệnh đề: whereas / while',
    ans: {
      summary:
        "Dùng để đối chiếu trực tiếp hai mệnh đề trái ngược trong cùng một câu. Đây là liên từ tương phản đắc lực nhất cho đoạn so sánh.",
      points: [
        "Công thức: [Mệnh đề A], whereas/while [mệnh đề B trái chiều].",
        "Hai vế phải nêu hai đối tượng/khía cạnh đối lập rõ ràng để phép so sánh có nghĩa.",
        "Lưu ý: \"while\" còn nghĩa thời gian, nhưng trong tương phản nó đồng nghĩa \"whereas\".",
      ],
      phrases: [
        "[clause], whereas + [clause]",
        "Whereas + [clause], [clause]",
        "[clause], while + [clause]",
      ],
      examples: [
        "City life offers convenience, whereas rural life provides peace and fresh air.",
        "Some students learn best through reading, whereas others prefer practical, hands-on activities.",
        "Wealthy nations consume vast amounts of energy, whereas poorer nations contribute very little to emissions.",
        "Older workers value job security, while younger employees tend to prioritise flexibility.",
        "Online shopping is convenient, whereas physical stores allow customers to inspect products first.",
        "Public healthcare is free at the point of use, whereas private care requires expensive insurance.",
        "Cars give people freedom, whereas public transport reduces both cost and pollution.",
        "Some governments invest heavily in prevention, whereas others spend mainly on treatment.",
        "Traditional media is carefully edited, while social media spreads information almost instantly.",
        "Developed countries face an ageing population, whereas many developing countries have a young workforce.",
      ],
      sample:
        "Older generations generally regard a stable, lifelong career as the ideal, whereas younger workers increasingly value variety and personal growth.\nThe former prize security, while the latter are willing to accept uncertainty in exchange for fulfilment.",
    },
  },
  {
    id: 's_20',
    module: 'sentences',
    topic: 's-comparison',
    band: 'b8',
    type: 'structure',
    tags: ['comparison', 'correlation', 'the more'],
    title: 'Tỉ lệ thuận/nghịch: the more X, the more Y',
    ans: {
      summary:
        "Cấu trúc tương quan, dùng để diễn đạt khi một yếu tố tăng/giảm thì yếu tố kia thay đổi theo. Sắc thái sắc bén, thể hiện mối quan hệ logic.",
      points: [
        "Công thức: The + comparative + S + V, the + comparative + S + V.",
        "Có thể dùng nghịch: The more..., the less...; The higher..., the lower...",
        "Lưu ý: cả hai vế đều cần comparative; trật tự cân đối giữa hai mệnh đề.",
      ],
      phrases: [
        "The more + [clause], the more + [clause]",
        "The higher + [clause], the lower + [clause]",
        "The greater + [noun], the greater + [noun]",
      ],
      examples: [
        "The more cars there are on the roads, the worse urban air pollution becomes.",
        "The higher the level of education, the lower the rate of unemployment tends to be.",
        "The more time children spend on screens, the less they engage in physical activity.",
        "The greater a country's reliance on fossil fuels, the harder it is to meet climate targets.",
        "The more affordable public transport is, the fewer people choose to drive.",
        "The longer people work without rest, the less productive they ultimately become.",
        "The more a society invests in healthcare, the healthier its population is likely to be.",
        "The wider the gap between rich and poor, the greater the risk of social tension.",
        "The more news we consume online, the harder it becomes to separate fact from opinion.",
        "The earlier children learn a language, the more fluently they tend to speak it as adults.",
      ],
      sample:
        "The more heavily a city depends on private vehicles, the more congested and polluted it inevitably becomes.\nConversely, the greater the investment in efficient public transport, the easier it is to break this cycle.",
    },
  },
  {
    id: 's_21',
    module: 'sentences',
    topic: 's-comparison',
    band: 'b8',
    type: 'structure',
    tags: ['comparison', 'superlative', 'by far'],
    title: 'So sánh nhất + nhấn mạnh: the most... by far / one of the...',
    ans: {
      summary:
        "Dùng để nêu bật một đối tượng nổi trội nhất, kèm trạng từ nhấn mạnh \"by far\". Rất hiệu quả để mở đầu hoặc nhấn mạnh luận điểm chính.",
      points: [
        "Công thức: [A] is (by far) the most + adj + danh từ; one of the + most + adj + DANH TỪ SỐ NHIỀU.",
        "\"by far\" tăng cường so sánh nhất; đặt trước hoặc sau cụm so sánh nhất.",
        "Lưu ý: \"one of the\" luôn theo sau bằng danh từ số nhiều và động từ chia số ít.",
      ],
      phrases: [
        "[A] is by far the most + [adjective] + [noun]",
        "[A] is one of the most + [adjective] + [plural noun]",
        "[A] is among the + [superlative] + [plural noun]",
      ],
      examples: [
        "Climate change is by far the most serious threat facing humanity today.",
        "Air pollution is one of the most pressing problems in rapidly growing cities.",
        "Education is by far the most powerful tool for lifting people out of poverty.",
        "Cancer remains one of the leading causes of death in developed countries.",
        "Traffic congestion is by far the biggest complaint among city commuters.",
        "Renewable energy is among the most promising solutions to the energy crisis.",
        "Unemployment is one of the most damaging consequences of an economic recession.",
        "The internet is by far the most influential invention of the past century.",
        "Obesity has become one of the most widespread health problems in wealthy nations.",
        "Corruption is by far the greatest obstacle to development in many poorer countries.",
      ],
      sample:
        "Of all the challenges that modern cities face, traffic congestion is by far the most visible and frustrating.\nIt is one of the main reasons residents report falling levels of satisfaction with urban life.",
    },
  },

  // ===================== s-example =====================
  {
    id: 's_22',
    module: 'sentences',
    topic: 's-example',
    band: 'b6',
    type: 'structure',
    tags: ['example', 'for instance', 'illustration'],
    title: 'Đưa ví dụ cơ bản: for example / for instance',
    ans: {
      summary:
        "Cấu trúc dẫn ví dụ phổ biến nhất, dùng để minh hoạ cho luận điểm vừa nêu. Nền tảng để phát triển ý trong thân bài.",
      points: [
        "Công thức: [Câu luận điểm]. For example/For instance, [câu ví dụ].",
        "Đứng đầu câu mới và theo sau bằng dấu phẩy; có thể chèn giữa câu (..., for example, ...).",
        "Lưu ý: ví dụ phải minh hoạ trực tiếp cho luận điểm, không lạc đề.",
      ],
      phrases: [
        "For example, + [clause]",
        "For instance, + [clause]",
        "To give an example, + [clause]",
      ],
      examples: [
        "Many cities are tackling pollution with bold policies. For example, several have banned diesel cars from their centres.",
        "Technology has transformed education. For instance, students can now attend lectures from anywhere in the world.",
        "Small lifestyle changes can improve health. For example, walking to work burns calories and reduces stress.",
        "Governments can encourage recycling in many ways. For instance, some charge households for the waste they throw away.",
        "Renewable energy is becoming mainstream. For example, Denmark now generates much of its electricity from wind.",
        "Crime can be reduced through prevention. For instance, better street lighting often deters burglary.",
        "Remote work offers clear advantages. For example, it allows parents to spend more time with their children.",
        "The media shapes public opinion. For instance, constant coverage of crime can make people feel unsafe.",
        "Cities can become greener with simple measures. For example, planting trees along streets lowers temperatures.",
        "Healthy eating habits start young. For instance, schools that ban sugary drinks see fewer overweight pupils.",
      ],
      sample:
        "Governments can do a great deal to reduce traffic in city centres.\nFor example, London charges drivers a fee to enter its busiest districts, and this has noticeably cut both congestion and pollution.",
    },
  },
  {
    id: 's_23',
    module: 'sentences',
    topic: 's-example',
    band: 'b7',
    type: 'structure',
    tags: ['example', 'a case in point', 'evidence'],
    title: 'Dẫn chứng tiêu biểu: A case in point is...',
    ans: {
      summary:
        "Dùng để giới thiệu một ví dụ cụ thể, điển hình nhằm củng cố luận điểm. Sắc thái trang trọng, học thuật hơn \"for example\".",
      points: [
        "Công thức: A case in point is + DANH TỪ. Hoặc: A case in point is + [mệnh đề].",
        "Thường đứng ngay sau câu nêu luận điểm tổng quát để đưa ra minh chứng.",
        "Đồng nghĩa: A good/clear example of this is...; A telling example is...",
      ],
      phrases: [
        "A case in point is + [noun/clause]",
        "A clear example of this is + [noun]",
        "A telling example is + [noun]",
      ],
      examples: [
        "Some countries have dramatically cut emissions. A case in point is Sweden, which now relies heavily on clean energy.",
        "Technology can widen inequality. A clear example of this is the digital divide between rich and poor students.",
        "Overtourism can ruin the very places it celebrates. A case in point is Venice, which is overwhelmed by visitors.",
        "Strict regulation can change behaviour. A telling example is the sharp fall in smoking after public bans.",
        "Investment in cycling pays off. A case in point is Amsterdam, where bicycles outnumber cars in the city centre.",
        "Automation is reshaping the workforce. A clear example of this is the replacement of cashiers by self-service tills.",
        "Poor planning worsens flooding. A case in point is the paving over of green spaces that once absorbed rainwater.",
        "Education can break the cycle of poverty. A telling example is the rise of free online learning platforms.",
        "Misinformation spreads fast online. A case in point is the rapid circulation of false health claims during pandemics.",
        "Public health campaigns can succeed. A clear example of this is the widespread adoption of seat belts.",
      ],
      sample:
        "Well-designed policies can persuade citizens to abandon their cars for cleaner alternatives.\nA case in point is Copenhagen, where decades of investment in cycle lanes have made the bicycle the most popular way to get around.",
    },
  },
  {
    id: 's_24',
    module: 'sentences',
    topic: 's-example',
    band: 'b6',
    type: 'structure',
    tags: ['example', 'such as', 'listing'],
    title: 'Liệt kê ví dụ: such as / including',
    ans: {
      summary:
        "Dùng để đưa ví dụ ngay trong câu bằng cách liệt kê, không cần tách thành câu mới. Giúp câu cô đọng và giàu thông tin.",
      points: [
        "Công thức: ...DANH TỪ + such as / including + [ví dụ 1, ví dụ 2 và ví dụ 3].",
        "Theo sau là danh từ/cụm danh từ làm ví dụ; không cần mệnh đề đầy đủ.",
        "Lưu ý: \"such as\" không cần dấu phẩy phía trước nếu ví dụ là thiết yếu; \"including\" tương tự.",
      ],
      phrases: [
        "[noun] such as + [examples]",
        "[noun], including + [examples]",
        "[noun], particularly + [example]",
      ],
      examples: [
        "Renewable sources such as solar, wind and hydropower are reducing our reliance on coal.",
        "Many illnesses, including diabetes and heart disease, are linked to poor diet.",
        "Digital skills such as coding and data analysis are increasingly valued by employers.",
        "Several global cities, including Tokyo and Singapore, have built world-class transport networks.",
        "Harmful habits such as smoking and excessive drinking shorten life expectancy considerably.",
        "Public spaces such as parks and libraries improve the quality of urban life.",
        "Many subjects, including history and literature, develop critical thinking skills.",
        "Endangered animals such as tigers and rhinos are threatened by illegal hunting.",
        "Online platforms, including social media and streaming services, dominate young people's free time.",
        "Basic services such as healthcare and education should be accessible to everyone.",
      ],
      sample:
        "Clean technologies such as solar panels, wind turbines and electric vehicles are no longer experimental.\nMany nations, including Germany and China, are now investing in them on a massive scale.",
    },
  },
  {
    id: 's_25',
    module: 'sentences',
    topic: 's-example',
    band: 'b8',
    type: 'structure',
    tags: ['example', 'exemplified', 'passive'],
    title: 'Minh hoạ bị động: This is (well) exemplified by...',
    ans: {
      summary:
        "Cấu trúc bị động trang trọng để dẫn chứng, nâng cao tính học thuật. Phù hợp khi muốn nối ví dụ một cách tinh tế ở band 8.",
      points: [
        "Công thức: This is (well/clearly) exemplified by + DANH TỪ / V-ing.",
        "Biến thể: This can be seen in...; This is illustrated by...; ...as can be seen in...",
        "Lưu ý: theo sau là danh từ/cụm danh từ; tránh đặt cả mệnh đề sau \"exemplified by\".",
      ],
      phrases: [
        "This is well exemplified by + [noun]",
        "This is clearly illustrated by + [noun]",
        "This can be seen in + [noun]",
      ],
      examples: [
        "Technology can deepen social isolation. This is well exemplified by people who scroll through phones instead of talking.",
        "Strong environmental laws produce results. This is clearly illustrated by the recovery of rivers once choked with waste.",
        "Cities can reinvent themselves. This can be seen in former industrial districts transformed into cultural hubs.",
        "Prevention saves lives and money. This is well exemplified by the steep decline in deaths from preventable diseases.",
        "Education changes economic destinies. This is clearly illustrated by the success of free scholarship programmes.",
        "Overconsumption harms the planet. This can be seen in the mountains of waste produced by fast fashion.",
        "Smart policy can curb pollution. This is well exemplified by the rise in air quality after coal plants were closed.",
        "Public attitudes can shift quickly. This is clearly illustrated by the rapid acceptance of recycling in many households.",
        "Automation is transforming industries. This can be seen in the spread of robots across modern warehouses.",
        "Good urban design encourages activity. This is well exemplified by cities that prioritise walking and cycling.",
      ],
      sample:
        "Sensible regulation can transform public behaviour without harming the economy.\nThis is well exemplified by the introduction of plastic bag charges, which dramatically reduced waste almost overnight.",
    },
  },
  {
    id: 's_26',
    module: 'sentences',
    topic: 's-example',
    band: 'b7',
    type: 'structure',
    tags: ['example', 'take as an example', 'spoken-written'],
    title: 'Lấy X làm ví dụ: Take X as an example',
    ans: {
      summary:
        "Cách dẫn ví dụ chủ động, mời người đọc cùng xem xét một trường hợp cụ thể. Linh hoạt, dễ dùng để mở rộng ý trong thân bài.",
      points: [
        "Công thức: Take + DANH TỪ + as an example. Sau đó phát triển bằng câu giải thích.",
        "Biến thể: Consider + DANH TỪ.; Let us take + DANH TỪ + as an example.",
        "Lưu ý: sau khi nêu ví dụ, cần một câu giải thích nó chứng minh điều gì.",
      ],
      phrases: [
        "Take + [noun] as an example.",
        "Consider + [noun].",
        "Let us take the case of + [noun].",
      ],
      examples: [
        "Take Singapore as an example. Strict planning has turned a small island into one of the greenest cities on earth.",
        "Consider the smartphone. Within a decade it has reshaped how we work, shop and communicate.",
        "Take electric cars as an example. As prices fall, sales are rising faster than almost anyone predicted.",
        "Consider plastic pollution. A single bottle can take hundreds of years to break down in the ocean.",
        "Take the rise of remote work as an example. Many companies now find that productivity has actually increased.",
        "Consider the impact of social media. It can spread both vital information and dangerous rumours within minutes.",
        "Take vaccination programmes as an example. They have eliminated diseases that once killed millions.",
        "Consider the housing crisis. In many cities, even well-paid workers can no longer afford to buy a home.",
        "Take recycling schemes as an example. When they are made simple and free, participation rises dramatically.",
        "Consider the ageing population. It is placing unprecedented pressure on pensions and healthcare alike.",
      ],
      sample:
        "Practical incentives often change behaviour more effectively than appeals to conscience.\nTake congestion charging as an example: once drivers had to pay to enter the city centre, many quickly switched to buses and trains.",
    },
  },
  {
    id: 's_27',
    module: 'sentences',
    topic: 's-example',
    band: 'b7',
    type: 'structure',
    tags: ['example', 'statistics', 'evidence'],
    title: 'Dẫn chứng bằng số liệu: Studies show that / According to...',
    ans: {
      summary:
        "Dùng để củng cố luận điểm bằng nghiên cứu hoặc số liệu, tăng tính thuyết phục. Sắc thái khách quan, đáng tin.",
      points: [
        "Công thức: Studies/Research show(s) that + [mệnh đề]; According to + nguồn, + [mệnh đề].",
        "Trong IELTS không cần nguồn thật; có thể dùng \"research suggests\", \"evidence indicates\".",
        "Lưu ý: \"research\" là danh từ không đếm được (research shows, KHÔNG researches).",
      ],
      phrases: [
        "Studies show that + [clause]",
        "Research suggests that + [clause]",
        "According to recent figures, + [clause]",
        "Evidence indicates that + [clause]",
      ],
      examples: [
        "Studies show that students who sleep well perform significantly better in exams.",
        "Research suggests that even short daily walks can reduce the risk of heart disease.",
        "According to recent figures, renewable energy now supplies a growing share of global electricity.",
        "Evidence indicates that bilingual children develop stronger problem-solving skills.",
        "Studies show that air pollution is linked to thousands of premature deaths each year.",
        "Research suggests that flexible working arrangements improve employee satisfaction.",
        "According to recent figures, the number of electric vehicles on the road has tripled in five years.",
        "Evidence indicates that early childhood education improves outcomes later in life.",
        "Studies show that excessive screen time is associated with poorer sleep among teenagers.",
        "Research suggests that green spaces in cities help lower residents' stress levels.",
      ],
      sample:
        "There is growing evidence that physical activity protects not only the body but also the mind.\nStudies show that people who exercise regularly are markedly less likely to suffer from depression, and research suggests the benefits appear after only a few weeks.",
    },
  },
  {
    id: 's_28',
    module: 'sentences',
    topic: 's-example',
    band: 'b8',
    type: 'template',
    tags: ['example', 'point-evidence-explain', 'paragraph'],
    title: 'Khung phát triển ý: Điểm - Ví dụ - Giải thích (PEE)',
    ans: {
      summary:
        "Khung mẫu để xây dựng một đoạn thân bài hoàn chỉnh: nêu luận điểm, đưa ví dụ, rồi giải thích ví dụ liên hệ luận điểm thế nào. Đây là xương sống của band 7-8.",
      points: [
        "Bước 1 - Point: nêu câu chủ đề (topic sentence) khẳng định luận điểm.",
        "Bước 2 - Evidence: dẫn ví dụ cụ thể bằng for example / a case in point / take... as an example.",
        "Bước 3 - Explain: giải thích ví dụ chứng minh luận điểm ra sao và liên hệ lại câu hỏi.",
      ],
      phrases: [
        "[Point]: One major reason is that + [clause]",
        "[Evidence]: A case in point is + [noun]",
        "[Explain]: This clearly demonstrates that + [clause]",
      ],
      examples: [
        "Point: Investment in public transport is the most effective way to ease congestion.",
        "Evidence: A case in point is Curitiba in Brazil, which built a fast, affordable bus network.",
        "Explain: This clearly demonstrates that good infrastructure can persuade drivers to leave their cars at home.",
        "Point: Early education has a lasting impact on a child's future.",
        "Evidence: For example, children who attend quality preschools tend to earn more as adults.",
        "Explain: This shows that spending on the early years yields benefits that last a lifetime.",
        "Point: Strict regulation can rapidly change consumer behaviour.",
        "Evidence: Take the plastic bag charge as an example; usage fell by over eighty per cent within a year.",
        "Explain: This indicates that small financial incentives can achieve what years of campaigns could not.",
        "Point: Remote work can benefit both employees and the environment, as fewer commutes mean lower emissions.",
      ],
      sample:
        "Investment in public transport is by far the most effective way to reduce urban congestion.\nA case in point is Curitiba in Brazil, where an efficient and affordable bus network persuaded huge numbers of commuters to give up driving.\nThis clearly demonstrates that, when reliable alternatives exist, people will readily abandon their cars, easing both traffic and pollution.",
    },
  },
];
