import type { Card } from './types';

export const VOCAB_CARDS: Card[] = [
  // ===================== EDUCATION =====================
  {
    id: 'v_1',
    module: 'vocab',
    topic: 'v-education',
    band: 'b7',
    type: 'vocab',
    tags: ['education', 'collocation', 'core'],
    title: 'Giáo dục: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Bộ collocation nền tảng để viết về giáo dục một cách tự nhiên ở band 7-8.',
      points: [
        'higher education = giáo dục bậc cao (đại học, sau đại học)',
        'compulsory education = giáo dục bắt buộc',
        'a well-rounded education = một nền giáo dục toàn diện',
        "to acquire knowledge = tiếp thu kiến thức",
        'to develop critical thinking skills = phát triển tư duy phản biện',
        'to pursue a degree = theo đuổi một tấm bằng',
        'academic performance = thành tích học tập',
        'a rigorous curriculum = chương trình học khắt khe',
        'lifelong learning = học tập suốt đời',
        'to bridge the skills gap = thu hẹp khoảng cách kỹ năng',
      ],
      phrases: [
        'higher education',
        'compulsory education',
        'a well-rounded education',
        'to acquire knowledge',
        'to develop critical thinking skills',
        'to pursue a degree',
        'academic performance',
        'a rigorous curriculum',
        'lifelong learning',
        'to bridge the skills gap',
      ],
    },
  },
  {
    id: 'v_2',
    module: 'vocab',
    topic: 'v-education',
    band: 'b7',
    type: 'vocab',
    tags: ['education', 'verbs', 'nouns'],
    title: 'Giáo dục: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng kèm collocation cho chủ đề giáo dục.',
      points: [
        'to instil values in students = gieo các giá trị cho học sinh',
        'to broaden horizons = mở rộng tầm nhìn',
        'to foster creativity = nuôi dưỡng sự sáng tạo',
        'to retain information = ghi nhớ thông tin',
        'tuition fees = học phí',
        'vocational training = đào tạo nghề',
        'acquisition of practical skills = sự tiếp thu kỹ năng thực hành',
        'rote learning = học vẹt',
        'to nurture talent = bồi dưỡng tài năng',
        'an enriching learning experience = trải nghiệm học tập giàu giá trị',
      ],
      phrases: [
        'to instil values in students',
        'to broaden horizons',
        'to foster creativity',
        'to retain information',
        'tuition fees',
        'vocational training',
        'acquisition of practical skills',
        'rote learning',
        'to nurture talent',
        'an enriching learning experience',
      ],
    },
  },
  {
    id: 'v_3',
    module: 'vocab',
    topic: 'v-education',
    band: 'b7',
    type: 'vocab',
    tags: ['education', 'idea', 'lexis'],
    title: 'Giáo dục: Idea + lexis',
    ans: {
      summary: 'Hai luận điểm phổ biến và vốn từ học thuật để diễn đạt chúng.',
      points: [
        'Idea 1: Giáo dục đại học giúp cải thiện triển vọng nghề nghiệp và thu nhập.',
        'Idea 2: Học nghề thực tiễn đôi khi giá trị hơn bằng cấp hàn lâm.',
        'Idea 3: Công nghệ đang chuyển đổi cách dạy và học.',
      ],
      phrases: [
        'to enhance employment prospects',
        'to command a higher salary',
        'a competitive edge in the job market',
        'hands-on, job-ready skills',
        'to address the demands of the labour market',
        'to facilitate personalised learning',
        'to democratise access to education',
        'remote and blended learning',
      ],
    },
  },
  {
    id: 'v_4',
    module: 'vocab',
    topic: 'v-education',
    band: 'b8',
    type: 'vocab',
    tags: ['education', 'adjectives', 'advanced'],
    title: 'Giáo dục: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm nâng band khi bàn về chất lượng và tác động của giáo dục.',
      points: [
        'intellectually stimulating = kích thích trí tuệ',
        'academically gifted = có năng khiếu học thuật',
        'an underfunded school system = hệ thống trường thiếu kinh phí',
        'a one-size-fits-all approach = cách tiếp cận rập khuôn cho mọi người',
        'detrimental to learning = có hại cho việc học',
        'conducive to learning = thuận lợi cho việc học',
        'an overly theoretical syllabus = giáo trình quá nặng lý thuyết',
        'a holistic approach to education = cách tiếp cận giáo dục toàn diện',
      ],
      phrases: [
        'intellectually stimulating',
        'academically gifted',
        'an underfunded school system',
        'a one-size-fits-all approach',
        'detrimental to learning',
        'conducive to learning',
        'an overly theoretical syllabus',
        'a holistic approach to education',
      ],
    },
  },
  {
    id: 'v_5',
    module: 'vocab',
    topic: 'v-education',
    band: 'b8',
    type: 'sample',
    tags: ['education', 'sample', 'model'],
    title: 'Giáo dục: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu hoàn chỉnh dùng vốn từ giáo dục một cách tự nhiên.',
      points: [
        'Dùng collocation trong câu trọn vẹn thay vì liệt kê từ rời.',
      ],
      examples: [
        "A well-rounded education does far more than transmit knowledge; it fosters creativity and equips young people with the critical thinking skills they need to thrive.",
        "While a university degree can enhance employment prospects, vocational training often provides the hands-on, job-ready skills that employers value most.",
        "Schools in deprived areas are frequently underfunded, which makes it difficult to create an environment that is genuinely conducive to learning.",
        "Online platforms have begun to democratise access to education, allowing learners to pursue a degree regardless of their geographical location.",
      ],
      sample:
        "A well-rounded education should not rely on rote learning alone. Instead, a rigorous yet intellectually stimulating curriculum that fosters critical thinking gives students a competitive edge in the labour market and lays the foundation for lifelong learning.",
    },
  },

  // ===================== ENVIRONMENT =====================
  {
    id: 'v_6',
    module: 'vocab',
    topic: 'v-environment',
    band: 'b7',
    type: 'vocab',
    tags: ['environment', 'collocation', 'core'],
    title: 'Môi trường: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Collocation nền tảng về biến đổi khí hậu và ô nhiễm.',
      points: [
        'carbon emissions = khí thải carbon',
        'greenhouse gases = khí nhà kính',
        'global warming = sự nóng lên toàn cầu',
        'depletion of natural resources = sự cạn kiệt tài nguyên thiên nhiên',
        'to mitigate the effects of climate change = giảm thiểu tác động của biến đổi khí hậu',
        'to adopt eco-friendly practices = áp dụng các thói quen thân thiện môi trường',
        'renewable energy sources = các nguồn năng lượng tái tạo',
        'fossil fuels = nhiên liệu hóa thạch',
        'to reduce our carbon footprint = giảm dấu chân carbon',
        'environmental degradation = sự suy thoái môi trường',
        'biodiversity loss = mất đa dạng sinh học',
      ],
      phrases: [
        'carbon emissions',
        'greenhouse gases',
        'global warming',
        'depletion of natural resources',
        'to mitigate the effects of climate change',
        'to adopt eco-friendly practices',
        'renewable energy sources',
        'fossil fuels',
        'to reduce our carbon footprint',
        'environmental degradation',
        'biodiversity loss',
      ],
    },
  },
  {
    id: 'v_7',
    module: 'vocab',
    topic: 'v-environment',
    band: 'b7',
    type: 'vocab',
    tags: ['environment', 'verbs', 'nouns'],
    title: 'Môi trường: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng để bàn về bảo vệ môi trường.',
      points: [
        'to curb pollution = kiềm chế ô nhiễm',
        'to conserve resources = bảo tồn tài nguyên',
        'to combat deforestation = chống nạn phá rừng',
        'to phase out single-use plastics = loại bỏ dần nhựa dùng một lần',
        'waste management = quản lý rác thải',
        'carbon-neutral targets = các mục tiêu trung hòa carbon',
        'to offset emissions = bù đắp lượng phát thải',
        'conservation efforts = các nỗ lực bảo tồn',
        'to harness solar power = khai thác năng lượng mặt trời',
        'sustainable development = phát triển bền vững',
      ],
      phrases: [
        'to curb pollution',
        'to conserve resources',
        'to combat deforestation',
        'to phase out single-use plastics',
        'waste management',
        'carbon-neutral targets',
        'to offset emissions',
        'conservation efforts',
        'to harness solar power',
        'sustainable development',
      ],
    },
  },
  {
    id: 'v_8',
    module: 'vocab',
    topic: 'v-environment',
    band: 'b7',
    type: 'vocab',
    tags: ['environment', 'idea', 'lexis'],
    title: 'Môi trường: Idea + lexis',
    ans: {
      summary: 'Luận điểm phổ biến và vốn từ học thuật để trình bày.',
      points: [
        'Idea 1: Cá nhân và chính phủ cùng chia sẻ trách nhiệm bảo vệ môi trường.',
        'Idea 2: Tăng trưởng kinh tế thường gây hại cho môi trường.',
        'Idea 3: Năng lượng tái tạo là chìa khóa cho tương lai bền vững.',
      ],
      phrases: [
        'a collective responsibility',
        'to impose stricter regulations',
        'at the expense of the environment',
        'to strike a balance between growth and sustainability',
        'a transition to clean energy',
        'to wean society off fossil fuels',
        'to safeguard the planet for future generations',
        'an irreversible impact on ecosystems',
      ],
    },
  },
  {
    id: 'v_9',
    module: 'vocab',
    topic: 'v-environment',
    band: 'b8',
    type: 'vocab',
    tags: ['environment', 'adjectives', 'advanced'],
    title: 'Môi trường: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm cao cấp giúp nâng band khi viết về môi trường.',
      points: [
        'environmentally sustainable = bền vững về mặt môi trường',
        'ecologically fragile = mong manh về mặt sinh thái',
        'a pressing environmental concern = một mối lo môi trường cấp bách',
        'an alarming rate of deforestation = tốc độ phá rừng đáng báo động',
        'detrimental to wildlife = có hại cho động vật hoang dã',
        'a finite supply of resources = nguồn tài nguyên hữu hạn',
        'far-reaching consequences = hậu quả sâu rộng',
        'a carbon-intensive industry = một ngành thải nhiều carbon',
      ],
      phrases: [
        'environmentally sustainable',
        'ecologically fragile',
        'a pressing environmental concern',
        'an alarming rate of deforestation',
        'detrimental to wildlife',
        'a finite supply of resources',
        'far-reaching consequences',
        'a carbon-intensive industry',
      ],
    },
  },
  {
    id: 'v_10',
    module: 'vocab',
    topic: 'v-environment',
    band: 'b8',
    type: 'sample',
    tags: ['environment', 'sample', 'model'],
    title: 'Môi trường: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu dùng từ vựng môi trường một cách tự nhiên.',
      points: [
        'Kết hợp collocation về khí hậu với mệnh đề nguyên nhân - kết quả.',
      ],
      examples: [
        "Reducing carbon emissions is no longer optional; it is a collective responsibility that requires governments to impose stricter regulations on carbon-intensive industries.",
        "Unless societies are weaned off fossil fuels, the depletion of natural resources will have far-reaching and largely irreversible consequences.",
        "A swift transition to renewable energy sources is widely regarded as the most effective way to mitigate the effects of climate change.",
        "Many companies are now adopting eco-friendly practices and setting carbon-neutral targets in order to reduce their carbon footprint.",
      ],
      sample:
        "Global warming is arguably the most pressing environmental concern of our time. To safeguard the planet for future generations, we must curb pollution, harness renewable energy and strike a balance between economic growth and sustainable development.",
    },
  },

  // ===================== TECHNOLOGY =====================
  {
    id: 'v_11',
    module: 'vocab',
    topic: 'v-technology',
    band: 'b7',
    type: 'vocab',
    tags: ['technology', 'collocation', 'core'],
    title: 'Công nghệ: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Collocation cốt lõi để bàn về công nghệ và số hóa.',
      points: [
        'technological advancements = những tiến bộ công nghệ',
        'the digital age = thời đại số',
        'artificial intelligence = trí tuệ nhân tạo',
        'to automate repetitive tasks = tự động hóa các tác vụ lặp đi lặp lại',
        'to streamline processes = tinh giản quy trình',
        'to keep pace with technology = bắt kịp công nghệ',
        'cutting-edge technology = công nghệ tiên tiến',
        'data privacy = quyền riêng tư dữ liệu',
        'the digital divide = khoảng cách số',
        'to enhance productivity = nâng cao năng suất',
        'social media platforms = các nền tảng mạng xã hội',
      ],
      phrases: [
        'technological advancements',
        'the digital age',
        'artificial intelligence',
        'to automate repetitive tasks',
        'to streamline processes',
        'to keep pace with technology',
        'cutting-edge technology',
        'data privacy',
        'the digital divide',
        'to enhance productivity',
        'social media platforms',
      ],
    },
  },
  {
    id: 'v_12',
    module: 'vocab',
    topic: 'v-technology',
    band: 'b7',
    type: 'vocab',
    tags: ['technology', 'verbs', 'nouns'],
    title: 'Công nghệ: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng cho chủ đề công nghệ.',
      points: [
        'to revolutionise an industry = tạo cách mạng cho một ngành',
        'to disrupt traditional business models = phá vỡ mô hình kinh doanh truyền thống',
        'to safeguard personal data = bảo vệ dữ liệu cá nhân',
        'to rely heavily on devices = phụ thuộc nặng nề vào thiết bị',
        'screen time = thời gian dùng màn hình',
        'technological dependence = sự phụ thuộc công nghệ',
        'a security breach = một vụ rò rỉ bảo mật',
        'to roll out a new system = triển khai hệ thống mới',
        'to bridge the digital divide = thu hẹp khoảng cách số',
        'instant access to information = truy cập thông tin tức thì',
      ],
      phrases: [
        'to revolutionise an industry',
        'to disrupt traditional business models',
        'to safeguard personal data',
        'to rely heavily on devices',
        'screen time',
        'technological dependence',
        'a security breach',
        'to roll out a new system',
        'to bridge the digital divide',
        'instant access to information',
      ],
    },
  },
  {
    id: 'v_13',
    module: 'vocab',
    topic: 'v-technology',
    band: 'b7',
    type: 'vocab',
    tags: ['technology', 'idea', 'lexis'],
    title: 'Công nghệ: Idea + lexis',
    ans: {
      summary: 'Luận điểm phổ biến và vốn từ để diễn đạt về công nghệ.',
      points: [
        'Idea 1: Tự động hóa nâng cao hiệu quả nhưng đe dọa việc làm.',
        'Idea 2: Mạng xã hội kết nối con người nhưng gây hại cho sức khỏe tinh thần.',
        'Idea 3: Công nghệ đặt ra lo ngại nghiêm trọng về quyền riêng tư.',
      ],
      phrases: [
        'to render certain jobs obsolete',
        'to boost efficiency and cut costs',
        'to foster a sense of connection',
        'to fuel anxiety and social comparison',
        'to collect vast amounts of personal data',
        'to erode individual privacy',
        'subject to misuse and surveillance',
        'a double-edged sword',
      ],
    },
  },
  {
    id: 'v_14',
    module: 'vocab',
    topic: 'v-technology',
    band: 'b8',
    type: 'vocab',
    tags: ['technology', 'adjectives', 'advanced'],
    title: 'Công nghệ: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm cao cấp khi đánh giá tác động công nghệ.',
      points: [
        'increasingly pervasive = ngày càng phổ biến khắp nơi',
        'technologically sophisticated = tinh vi về công nghệ',
        'a groundbreaking innovation = một phát kiến mang tính đột phá',
        'highly addictive by design = được thiết kế gây nghiện cao',
        'an over-reliance on technology = sự phụ thuộc thái quá vào công nghệ',
        'vulnerable to cyberattacks = dễ bị tấn công mạng',
        'a seamless user experience = trải nghiệm người dùng liền mạch',
        'a transformative impact = một tác động mang tính chuyển đổi',
      ],
      phrases: [
        'increasingly pervasive',
        'technologically sophisticated',
        'a groundbreaking innovation',
        'highly addictive by design',
        'an over-reliance on technology',
        'vulnerable to cyberattacks',
        'a seamless user experience',
        'a transformative impact',
      ],
    },
  },
  {
    id: 'v_15',
    module: 'vocab',
    topic: 'v-technology',
    band: 'b8',
    type: 'sample',
    tags: ['technology', 'sample', 'model'],
    title: 'Công nghệ: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu dùng từ vựng công nghệ tự nhiên.',
      points: [
        'Thể hiện cả mặt lợi và hại của công nghệ trong cùng một câu.',
      ],
      examples: [
        "Artificial intelligence can automate repetitive tasks and dramatically enhance productivity, yet it also threatens to render certain jobs obsolete.",
        "Although social media platforms foster a sense of connection, their highly addictive design can fuel anxiety and social comparison.",
        "As companies collect vast amounts of personal data, robust regulation is essential to safeguard individual privacy and prevent security breaches.",
        "Technology is a double-edged sword: it offers instant access to information but can also breed an unhealthy over-reliance on devices.",
      ],
      sample:
        "Technological advancements have a transformative impact on modern life. While cutting-edge tools streamline processes and boost efficiency, society must address the digital divide and protect data privacy if it hopes to keep pace with the digital age responsibly.",
    },
  },

  // ===================== HEALTH =====================
  {
    id: 'v_16',
    module: 'vocab',
    topic: 'v-health',
    band: 'b7',
    type: 'vocab',
    tags: ['health', 'collocation', 'core'],
    title: 'Sức khỏe: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Collocation nền tảng về sức khỏe và lối sống.',
      points: [
        'a balanced diet = một chế độ ăn cân bằng',
        'to lead a sedentary lifestyle = sống lối sống ít vận động',
        'to maintain a healthy weight = duy trì cân nặng khỏe mạnh',
        'physical and mental wellbeing = sức khỏe thể chất và tinh thần',
        'preventive healthcare = chăm sóc sức khỏe phòng ngừa',
        'to put a strain on the healthcare system = gây áp lực lên hệ thống y tế',
        'chronic diseases = các bệnh mãn tính',
        'life expectancy = tuổi thọ trung bình',
        'to take a toll on health = gây tổn hại sức khỏe',
        'access to medical care = khả năng tiếp cận chăm sóc y tế',
        'mental health issues = các vấn đề sức khỏe tinh thần',
      ],
      phrases: [
        'a balanced diet',
        'to lead a sedentary lifestyle',
        'to maintain a healthy weight',
        'physical and mental wellbeing',
        'preventive healthcare',
        'to put a strain on the healthcare system',
        'chronic diseases',
        'life expectancy',
        'to take a toll on health',
        'access to medical care',
        'mental health issues',
      ],
    },
  },
  {
    id: 'v_17',
    module: 'vocab',
    topic: 'v-health',
    band: 'b7',
    type: 'vocab',
    tags: ['health', 'verbs', 'nouns'],
    title: 'Sức khỏe: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng cho chủ đề sức khỏe.',
      points: [
        'to promote healthy habits = khuyến khích thói quen lành mạnh',
        'to prevent the spread of disease = ngăn dịch bệnh lây lan',
        'to alleviate stress = làm giảm căng thẳng',
        'to boost the immune system = tăng cường hệ miễn dịch',
        'a sedentary lifestyle = lối sống ít vận động',
        'obesity rates = tỷ lệ béo phì',
        'healthcare provision = sự cung cấp dịch vụ y tế',
        'to subsidise medical treatment = trợ cấp chi phí điều trị',
        'an ageing population = dân số già hóa',
        'to raise public awareness = nâng cao nhận thức cộng đồng',
      ],
      phrases: [
        'to promote healthy habits',
        'to prevent the spread of disease',
        'to alleviate stress',
        'to boost the immune system',
        'a sedentary lifestyle',
        'obesity rates',
        'healthcare provision',
        'to subsidise medical treatment',
        'an ageing population',
        'to raise public awareness',
      ],
    },
  },
  {
    id: 'v_18',
    module: 'vocab',
    topic: 'v-health',
    band: 'b7',
    type: 'vocab',
    tags: ['health', 'idea', 'lexis'],
    title: 'Sức khỏe: Idea + lexis',
    ans: {
      summary: 'Luận điểm phổ biến và vốn từ để diễn đạt về sức khỏe.',
      points: [
        'Idea 1: Phòng bệnh hiệu quả và rẻ hơn chữa bệnh.',
        'Idea 2: Chính phủ nên đầu tư vào y tế công.',
        'Idea 3: Lối sống hiện đại gây ra nhiều vấn đề sức khỏe.',
      ],
      phrases: [
        'prevention is better than cure',
        'to ease the burden on hospitals',
        'to allocate funding to public health',
        'universal access to healthcare',
        'to combat the rise in obesity',
        'a fast-paced, stressful lifestyle',
        'the prevalence of junk food',
        'to encourage regular physical activity',
      ],
    },
  },
  {
    id: 'v_19',
    module: 'vocab',
    topic: 'v-health',
    band: 'b8',
    type: 'vocab',
    tags: ['health', 'adjectives', 'advanced'],
    title: 'Sức khỏe: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm cao cấp khi viết về sức khỏe và y tế.',
      points: [
        'physically and emotionally draining = vắt kiệt cả thể chất lẫn tinh thần',
        'a debilitating illness = một căn bệnh gây suy nhược',
        'preventable diseases = các bệnh có thể phòng ngừa',
        'an overstretched healthcare system = hệ thống y tế quá tải',
        'detrimental to long-term health = có hại cho sức khỏe lâu dài',
        'a sedentary, screen-bound lifestyle = lối sống ít vận động, gắn với màn hình',
        'nutritionally deficient = thiếu hụt dinh dưỡng',
        'a holistic approach to wellbeing = cách tiếp cận toàn diện về sức khỏe',
      ],
      phrases: [
        'physically and emotionally draining',
        'a debilitating illness',
        'preventable diseases',
        'an overstretched healthcare system',
        'detrimental to long-term health',
        'a sedentary, screen-bound lifestyle',
        'nutritionally deficient',
        'a holistic approach to wellbeing',
      ],
    },
  },
  {
    id: 'v_20',
    module: 'vocab',
    topic: 'v-health',
    band: 'b8',
    type: 'sample',
    tags: ['health', 'sample', 'model'],
    title: 'Sức khỏe: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu dùng từ vựng sức khỏe tự nhiên.',
      points: [
        'Gắn nguyên nhân lối sống với hậu quả sức khỏe và giải pháp.',
      ],
      examples: [
        "Because prevention is better than cure, investing in preventive healthcare can ease the burden on an already overstretched healthcare system.",
        "A sedentary lifestyle combined with the prevalence of junk food has driven up obesity rates and the incidence of preventable diseases.",
        "Maintaining a balanced diet and exercising regularly are widely recognised as the most effective ways to protect physical and mental wellbeing.",
        "An ageing population is placing an unprecedented strain on healthcare provision, forcing governments to allocate more funding to public health.",
      ],
      sample:
        "Modern life is increasingly fast-paced and stressful, which takes a serious toll on health. By promoting healthy habits and prioritising preventive healthcare, governments can reduce chronic diseases, improve life expectancy and relieve pressure on hospitals.",
    },
  },

  // ===================== CRIME =====================
  {
    id: 'v_21',
    module: 'vocab',
    topic: 'v-crime',
    band: 'b7',
    type: 'vocab',
    tags: ['crime', 'collocation', 'core'],
    title: 'Tội phạm & Pháp luật: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Collocation nền tảng về tội phạm và hệ thống pháp luật.',
      points: [
        'to commit a crime = phạm tội',
        'to deter potential offenders = răn đe tội phạm tiềm năng',
        'crime rate = tỷ lệ tội phạm',
        'to reduce reoffending = giảm tái phạm',
        'a custodial sentence = một bản án giam giữ',
        'the criminal justice system = hệ thống tư pháp hình sự',
        'to rehabilitate offenders = cải tạo người phạm tội',
        'law enforcement agencies = các cơ quan thực thi pháp luật',
        'to impose harsher penalties = áp dụng hình phạt nặng hơn',
        'the root causes of crime = nguyên nhân gốc rễ của tội phạm',
        'a deterrent effect = hiệu ứng răn đe',
      ],
      phrases: [
        'to commit a crime',
        'to deter potential offenders',
        'crime rate',
        'to reduce reoffending',
        'a custodial sentence',
        'the criminal justice system',
        'to rehabilitate offenders',
        'law enforcement agencies',
        'to impose harsher penalties',
        'the root causes of crime',
        'a deterrent effect',
      ],
    },
  },
  {
    id: 'v_22',
    module: 'vocab',
    topic: 'v-crime',
    band: 'b7',
    type: 'vocab',
    tags: ['crime', 'verbs', 'nouns'],
    title: 'Tội phạm & Pháp luật: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng cho chủ đề tội phạm.',
      points: [
        'to enforce the law = thực thi luật pháp',
        'to crack down on crime = mạnh tay với tội phạm',
        'to serve a prison sentence = thụ án tù',
        'to reintegrate into society = tái hòa nhập xã hội',
        'petty crime = tội vặt',
        'organised crime = tội phạm có tổ chức',
        'a repeat offender = kẻ tái phạm',
        'community service = lao động công ích',
        'to tackle the underlying causes = giải quyết nguyên nhân sâu xa',
        'an effective deterrent = một biện pháp răn đe hiệu quả',
      ],
      phrases: [
        'to enforce the law',
        'to crack down on crime',
        'to serve a prison sentence',
        'to reintegrate into society',
        'petty crime',
        'organised crime',
        'a repeat offender',
        'community service',
        'to tackle the underlying causes',
        'an effective deterrent',
      ],
    },
  },
  {
    id: 'v_23',
    module: 'vocab',
    topic: 'v-crime',
    band: 'b7',
    type: 'vocab',
    tags: ['crime', 'idea', 'lexis'],
    title: 'Tội phạm & Pháp luật: Idea + lexis',
    ans: {
      summary: 'Luận điểm phổ biến và vốn từ để diễn đạt về tội phạm.',
      points: [
        'Idea 1: Cải tạo hiệu quả hơn trừng phạt nghiêm khắc.',
        'Idea 2: Hình phạt nặng có tác dụng răn đe tội phạm.',
        'Idea 3: Nghèo đói và thất nghiệp là nguyên nhân gốc rễ của tội phạm.',
      ],
      phrases: [
        'to address the root causes rather than the symptoms',
        'to equip offenders with employable skills',
        'to break the cycle of crime',
        'to act as a powerful deterrent',
        'tougher sentencing',
        'poverty and social exclusion',
        'a lack of economic opportunity',
        'to drive people to crime',
      ],
    },
  },
  {
    id: 'v_24',
    module: 'vocab',
    topic: 'v-crime',
    band: 'b8',
    type: 'vocab',
    tags: ['crime', 'adjectives', 'advanced'],
    title: 'Tội phạm & Pháp luật: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm cao cấp khi bàn về tội phạm và hình phạt.',
      points: [
        'a counterproductive policy = một chính sách phản tác dụng',
        'overly punitive measures = các biện pháp trừng phạt quá khắc nghiệt',
        'a lenient sentence = một bản án khoan dung',
        'socially marginalised individuals = những cá nhân bị gạt ra ngoài lề xã hội',
        'a deeply ingrained problem = một vấn đề ăn sâu',
        'a proportionate punishment = một hình phạt tương xứng',
        'rehabilitative rather than punitive = mang tính cải tạo hơn là trừng phạt',
        'a surge in violent crime = sự gia tăng đột biến tội phạm bạo lực',
      ],
      phrases: [
        'a counterproductive policy',
        'overly punitive measures',
        'a lenient sentence',
        'socially marginalised individuals',
        'a deeply ingrained problem',
        'a proportionate punishment',
        'rehabilitative rather than punitive',
        'a surge in violent crime',
      ],
    },
  },
  {
    id: 'v_25',
    module: 'vocab',
    topic: 'v-crime',
    band: 'b8',
    type: 'sample',
    tags: ['crime', 'sample', 'model'],
    title: 'Tội phạm & Pháp luật: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu dùng từ vựng tội phạm tự nhiên.',
      points: [
        'Đối chiếu cải tạo và trừng phạt, gắn với nguyên nhân gốc rễ.',
      ],
      examples: [
        "Rather than relying solely on harsher penalties, governments should address the root causes of crime, such as poverty and social exclusion.",
        "Although a custodial sentence may act as a deterrent, programmes that rehabilitate offenders are often more effective at reducing reoffending.",
        "Equipping prisoners with employable skills helps them reintegrate into society and break the cycle of crime.",
        "Overly punitive measures can prove counterproductive, since they rarely tackle the underlying factors that drive people to crime.",
      ],
      sample:
        "A purely punitive approach to crime is increasingly seen as counterproductive. While law enforcement agencies must enforce the law firmly, a rehabilitative system that addresses the root causes of crime offers a more sustainable way to reduce reoffending.",
    },
  },

  // ===================== WORK & ECONOMY =====================
  {
    id: 'v_26',
    module: 'vocab',
    topic: 'v-work',
    band: 'b7',
    type: 'vocab',
    tags: ['work', 'collocation', 'core'],
    title: 'Việc làm & Kinh tế: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Collocation nền tảng về việc làm và kinh tế.',
      points: [
        'job satisfaction = sự hài lòng trong công việc',
        'a competitive salary = mức lương cạnh tranh',
        'work-life balance = sự cân bằng công việc - cuộc sống',
        'to climb the career ladder = leo lên nấc thang sự nghiệp',
        'job security = sự ổn định việc làm',
        'the unemployment rate = tỷ lệ thất nghiệp',
        'to boost economic growth = thúc đẩy tăng trưởng kinh tế',
        'a thriving economy = một nền kinh tế phát triển mạnh',
        'to create job opportunities = tạo ra cơ hội việc làm',
        'remote working = làm việc từ xa',
        'the gig economy = nền kinh tế việc làm tự do',
      ],
      phrases: [
        'job satisfaction',
        'a competitive salary',
        'work-life balance',
        'to climb the career ladder',
        'job security',
        'the unemployment rate',
        'to boost economic growth',
        'a thriving economy',
        'to create job opportunities',
        'remote working',
        'the gig economy',
      ],
    },
  },
  {
    id: 'v_27',
    module: 'vocab',
    topic: 'v-work',
    band: 'b7',
    type: 'vocab',
    tags: ['work', 'verbs', 'nouns'],
    title: 'Việc làm & Kinh tế: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng cho chủ đề việc làm.',
      points: [
        'to recruit and retain staff = tuyển dụng và giữ chân nhân viên',
        'to stimulate the economy = kích thích nền kinh tế',
        'to combat unemployment = chống thất nghiệp',
        'to enter the workforce = gia nhập lực lượng lao động',
        'a labour shortage = tình trạng thiếu lao động',
        'disposable income = thu nhập khả dụng',
        'to make ends meet = xoay xở đủ sống',
        'a stable source of income = một nguồn thu nhập ổn định',
        'to outsource jobs = thuê ngoài công việc',
        'to invest in human capital = đầu tư vào vốn con người',
      ],
      phrases: [
        'to recruit and retain staff',
        'to stimulate the economy',
        'to combat unemployment',
        'to enter the workforce',
        'a labour shortage',
        'disposable income',
        'to make ends meet',
        'a stable source of income',
        'to outsource jobs',
        'to invest in human capital',
      ],
    },
  },
  {
    id: 'v_28',
    module: 'vocab',
    topic: 'v-work',
    band: 'b7',
    type: 'vocab',
    tags: ['work', 'idea', 'lexis'],
    title: 'Việc làm & Kinh tế: Idea + lexis',
    ans: {
      summary: 'Luận điểm phổ biến và vốn từ để diễn đạt về việc làm.',
      points: [
        'Idea 1: Cân bằng công việc - cuộc sống quan trọng hơn lương cao.',
        'Idea 2: Làm việc từ xa mang lại lợi ích cho cả nhân viên và doanh nghiệp.',
        'Idea 3: Tự động hóa đe dọa việc làm truyền thống.',
      ],
      phrases: [
        'to prioritise wellbeing over financial reward',
        'to prevent burnout',
        'to enhance flexibility and autonomy',
        'to reduce commuting time and overheads',
        'to displace low-skilled workers',
        'to reskill and upskill the workforce',
        'to adapt to a changing labour market',
        'long-term financial stability',
      ],
    },
  },
  {
    id: 'v_29',
    module: 'vocab',
    topic: 'v-work',
    band: 'b8',
    type: 'vocab',
    tags: ['work', 'adjectives', 'advanced'],
    title: 'Việc làm & Kinh tế: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm cao cấp khi viết về công việc và kinh tế.',
      points: [
        'financially rewarding = mang lại lợi ích tài chính',
        'a highly competitive job market = thị trường việc làm cạnh tranh khốc liệt',
        'an economically deprived region = một vùng khó khăn về kinh tế',
        'a fulfilling and meaningful career = một sự nghiệp viên mãn và ý nghĩa',
        'increasingly precarious employment = việc làm ngày càng bấp bênh',
        'a buoyant economy = một nền kinh tế sôi động',
        'an economic downturn = một đợt suy thoái kinh tế',
        'a sustainable livelihood = một sinh kế bền vững',
      ],
      phrases: [
        'financially rewarding',
        'a highly competitive job market',
        'an economically deprived region',
        'a fulfilling and meaningful career',
        'increasingly precarious employment',
        'a buoyant economy',
        'an economic downturn',
        'a sustainable livelihood',
      ],
    },
  },
  {
    id: 'v_30',
    module: 'vocab',
    topic: 'v-work',
    band: 'b8',
    type: 'sample',
    tags: ['work', 'sample', 'model'],
    title: 'Việc làm & Kinh tế: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu dùng từ vựng việc làm tự nhiên.',
      points: [
        'Kết hợp lợi ích cá nhân và lợi ích kinh tế vĩ mô.',
      ],
      examples: [
        "For many employees, a healthy work-life balance now matters more than a competitive salary, as it helps prevent burnout.",
        "Remote working enhances flexibility and autonomy while allowing firms to reduce commuting time and overheads.",
        "As automation displaces low-skilled workers, governments must invest in human capital to reskill and upskill the workforce.",
        "Creating job opportunities in economically deprived regions is one of the most effective ways to stimulate the economy.",
      ],
      sample:
        "A fulfilling career offers far more than financial reward. In an increasingly competitive job market, employees value job security and work-life balance, while a thriving economy depends on policies that combat unemployment and invest in human capital.",
    },
  },

  // ===================== SOCIETY & FAMILY =====================
  {
    id: 'v_31',
    module: 'vocab',
    topic: 'v-society',
    band: 'b7',
    type: 'vocab',
    tags: ['society', 'collocation', 'core'],
    title: 'Xã hội & Gia đình: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Collocation nền tảng về xã hội và gia đình.',
      points: [
        'family values = các giá trị gia đình',
        'a close-knit family = một gia đình gắn bó',
        'to strengthen social bonds = củng cố các mối liên kết xã hội',
        'the generation gap = khoảng cách thế hệ',
        'gender equality = bình đẳng giới',
        'social cohesion = sự gắn kết xã hội',
        'to instil values in children = gieo các giá trị cho con cái',
        'the role of upbringing = vai trò của sự nuôi dạy',
        'a sense of belonging = cảm giác thuộc về',
        'social isolation = sự cô lập xã hội',
        'community spirit = tinh thần cộng đồng',
      ],
      phrases: [
        'family values',
        'a close-knit family',
        'to strengthen social bonds',
        'the generation gap',
        'gender equality',
        'social cohesion',
        'to instil values in children',
        'the role of upbringing',
        'a sense of belonging',
        'social isolation',
        'community spirit',
      ],
    },
  },
  {
    id: 'v_32',
    module: 'vocab',
    topic: 'v-society',
    band: 'b7',
    type: 'vocab',
    tags: ['society', 'verbs', 'nouns'],
    title: 'Xã hội & Gia đình: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng cho chủ đề xã hội.',
      points: [
        'to raise children = nuôi dạy con cái',
        'to bridge the generation gap = thu hẹp khoảng cách thế hệ',
        'to foster a sense of community = nuôi dưỡng tinh thần cộng đồng',
        'to break down social barriers = phá bỏ các rào cản xã hội',
        'parental guidance = sự định hướng của cha mẹ',
        'an extended family = gia đình mở rộng (nhiều thế hệ)',
        'social mobility = sự dịch chuyển xã hội',
        'to promote tolerance = thúc đẩy sự khoan dung',
        'a multicultural society = một xã hội đa văn hóa',
        'to combat discrimination = chống phân biệt đối xử',
      ],
      phrases: [
        'to raise children',
        'to bridge the generation gap',
        'to foster a sense of community',
        'to break down social barriers',
        'parental guidance',
        'an extended family',
        'social mobility',
        'to promote tolerance',
        'a multicultural society',
        'to combat discrimination',
      ],
    },
  },
  {
    id: 'v_33',
    module: 'vocab',
    topic: 'v-society',
    band: 'b7',
    type: 'vocab',
    tags: ['society', 'idea', 'lexis'],
    title: 'Xã hội & Gia đình: Idea + lexis',
    ans: {
      summary: 'Luận điểm phổ biến và vốn từ để diễn đạt về xã hội.',
      points: [
        'Idea 1: Cha mẹ ảnh hưởng lớn đến sự phát triển của trẻ.',
        'Idea 2: Cuộc sống hiện đại làm suy yếu mối quan hệ gia đình.',
        'Idea 3: Đa dạng văn hóa làm phong phú xã hội.',
      ],
      phrases: [
        'to shape a child character',
        'to serve as role models',
        'to lay the foundation for future success',
        'to erode traditional family ties',
        'increasingly fragmented households',
        'to enrich the cultural fabric of society',
        'to broaden perspectives',
        'a more inclusive and tolerant society',
      ],
    },
  },
  {
    id: 'v_34',
    module: 'vocab',
    topic: 'v-society',
    band: 'b8',
    type: 'vocab',
    tags: ['society', 'adjectives', 'advanced'],
    title: 'Xã hội & Gia đình: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm cao cấp khi viết về xã hội và gia đình.',
      points: [
        'a deeply rooted tradition = một truyền thống ăn sâu',
        'an increasingly individualistic society = một xã hội ngày càng đề cao cá nhân',
        'socially cohesive = gắn kết về mặt xã hội',
        'a nurturing environment = một môi trường nuôi dưỡng',
        'culturally diverse = đa dạng về văn hóa',
        'a tightly knit community = một cộng đồng gắn bó chặt chẽ',
        'morally formative years = những năm tháng hình thành đạo đức',
        'a profound influence on development = một ảnh hưởng sâu sắc đến sự phát triển',
      ],
      phrases: [
        'a deeply rooted tradition',
        'an increasingly individualistic society',
        'socially cohesive',
        'a nurturing environment',
        'culturally diverse',
        'a tightly knit community',
        'morally formative years',
        'a profound influence on development',
      ],
    },
  },
  {
    id: 'v_35',
    module: 'vocab',
    topic: 'v-society',
    band: 'b8',
    type: 'sample',
    tags: ['society', 'sample', 'model'],
    title: 'Xã hội & Gia đình: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu dùng từ vựng xã hội tự nhiên.',
      points: [
        'Liên kết vai trò gia đình với kết quả xã hội rộng hơn.',
      ],
      examples: [
        "Parents serve as role models and play a profound role in shaping a child character during their morally formative years.",
        "The demands of modern life have begun to erode traditional family ties, leaving households increasingly fragmented.",
        "A culturally diverse society enriches the cultural fabric of a nation and broadens the perspectives of its citizens.",
        "Strong family values and a genuine sense of belonging are essential for maintaining social cohesion.",
      ],
      sample:
        "The family remains the cornerstone of society. A close-knit family provides a nurturing environment that instils values in children, while a culturally diverse and socially cohesive community fosters tolerance and a lasting sense of belonging.",
    },
  },

  // ===================== GOVERNMENT & GLOBALISATION =====================
  {
    id: 'v_36',
    module: 'vocab',
    topic: 'v-government',
    band: 'b7',
    type: 'vocab',
    tags: ['government', 'collocation', 'core'],
    title: 'Chính phủ & Toàn cầu hóa: Cụm từ & collocation cốt lõi',
    ans: {
      summary: 'Collocation nền tảng về chính phủ và toàn cầu hóa.',
      points: [
        'government spending = chi tiêu chính phủ',
        'to allocate public funds = phân bổ ngân sách công',
        'to implement policies = triển khai chính sách',
        'public services = các dịch vụ công',
        'to raise taxes = tăng thuế',
        'economic globalisation = toàn cầu hóa kinh tế',
        'international trade = thương mại quốc tế',
        'cultural exchange = giao lưu văn hóa',
        'to bridge cultural differences = thu hẹp khác biệt văn hóa',
        'developing countries = các nước đang phát triển',
        'to stimulate economic growth = thúc đẩy tăng trưởng kinh tế',
      ],
      phrases: [
        'government spending',
        'to allocate public funds',
        'to implement policies',
        'public services',
        'to raise taxes',
        'economic globalisation',
        'international trade',
        'cultural exchange',
        'to bridge cultural differences',
        'developing countries',
        'to stimulate economic growth',
      ],
    },
  },
  {
    id: 'v_37',
    module: 'vocab',
    topic: 'v-government',
    band: 'b7',
    type: 'vocab',
    tags: ['government', 'verbs', 'nouns'],
    title: 'Chính phủ & Toàn cầu hóa: Động từ & danh từ chủ đề',
    ans: {
      summary: 'Động từ và danh từ thường dùng cho chủ đề chính phủ.',
      points: [
        'to invest in infrastructure = đầu tư vào hạ tầng',
        'to subsidise public transport = trợ giá giao thông công cộng',
        'to bridge the gap between rich and poor = thu hẹp khoảng cách giàu nghèo',
        'to enforce regulations = thực thi các quy định',
        'a multinational corporation = một tập đoàn đa quốc gia',
        'foreign investment = đầu tư nước ngoài',
        'the global economy = nền kinh tế toàn cầu',
        'to preserve local culture = bảo tồn văn hóa địa phương',
        'income inequality = bất bình đẳng thu nhập',
        'to promote international cooperation = thúc đẩy hợp tác quốc tế',
      ],
      phrases: [
        'to invest in infrastructure',
        'to subsidise public transport',
        'to bridge the gap between rich and poor',
        'to enforce regulations',
        'a multinational corporation',
        'foreign investment',
        'the global economy',
        'to preserve local culture',
        'income inequality',
        'to promote international cooperation',
      ],
    },
  },
  {
    id: 'v_38',
    module: 'vocab',
    topic: 'v-government',
    band: 'b7',
    type: 'vocab',
    tags: ['government', 'idea', 'lexis'],
    title: 'Chính phủ & Toàn cầu hóa: Idea + lexis',
    ans: {
      summary: 'Luận điểm phổ biến và vốn từ để diễn đạt về chính phủ.',
      points: [
        'Idea 1: Toàn cầu hóa thúc đẩy tăng trưởng nhưng đe dọa bản sắc địa phương.',
        'Idea 2: Chính phủ nên ưu tiên chi cho giáo dục và y tế.',
        'Idea 3: Các vấn đề toàn cầu cần hợp tác quốc tế.',
      ],
      phrases: [
        'to open up access to global markets',
        'to erode cultural identity',
        'a homogenisation of cultures',
        'to allocate resources to essential services',
        'to deliver the greatest benefit to society',
        'to transcend national borders',
        'a coordinated international response',
        'to tackle shared global challenges',
      ],
    },
  },
  {
    id: 'v_39',
    module: 'vocab',
    topic: 'v-government',
    band: 'b8',
    type: 'vocab',
    tags: ['government', 'adjectives', 'advanced'],
    title: 'Chính phủ & Toàn cầu hóa: Tính từ & cách diễn đạt nâng cao',
    ans: {
      summary: 'Tính từ và cụm cao cấp khi viết về chính phủ và toàn cầu hóa.',
      points: [
        'an interconnected world = một thế giới kết nối chặt chẽ',
        'economically interdependent = phụ thuộc lẫn nhau về kinh tế',
        'a far-sighted policy = một chính sách có tầm nhìn xa',
        'fiscally responsible = có trách nhiệm về tài khóa',
        'a glaring wealth gap = một khoảng cách giàu nghèo rõ rệt',
        'culturally homogenising = đồng nhất hóa văn hóa',
        'a disproportionate burden = một gánh nặng không cân xứng',
        'mutually beneficial trade = thương mại đôi bên cùng có lợi',
      ],
      phrases: [
        'an interconnected world',
        'economically interdependent',
        'a far-sighted policy',
        'fiscally responsible',
        'a glaring wealth gap',
        'culturally homogenising',
        'a disproportionate burden',
        'mutually beneficial trade',
      ],
    },
  },
  {
    id: 'v_40',
    module: 'vocab',
    topic: 'v-government',
    band: 'b8',
    type: 'sample',
    tags: ['government', 'sample', 'model'],
    title: 'Chính phủ & Toàn cầu hóa: Câu mẫu áp dụng',
    ans: {
      summary: 'Câu mẫu dùng từ vựng chính phủ và toàn cầu hóa tự nhiên.',
      points: [
        'Cân nhắc lợi ích và rủi ro của toàn cầu hóa, kèm vai trò chính phủ.',
      ],
      examples: [
        "Globalisation opens up access to global markets and stimulates economic growth, yet it can also erode cultural identity through the homogenisation of cultures.",
        "Governments should allocate public funds to essential services such as education and healthcare in order to deliver the greatest benefit to society.",
        "Because environmental problems transcend national borders, a coordinated international response is needed to tackle shared global challenges.",
        "Investing in infrastructure and attracting foreign investment can help bridge the gap between rich and poor in developing countries.",
      ],
      sample:
        "In an increasingly interconnected and economically interdependent world, globalisation brings both opportunity and risk. A far-sighted, fiscally responsible government must promote mutually beneficial trade while implementing policies that preserve local culture and narrow the glaring wealth gap.",
    },
  },
];
